version: 0.2
run-as: ubuntu

env:
  variables:
    HOME: "/home/ubuntu"
    UNITY_BUILD_METHOD: "CIBuilder.BuildProject"
    SOURCE_APK_PATH: "Builds/app.apk"
    OUTPUT_APK_BASENAME: "app"

phases:
  install:
    commands:
      - command -v git >/dev/null 2>&1 || { echo "git is required in the AMI"; exit 1; }
      - command -v git-lfs >/dev/null 2>&1 || { echo "git-lfs is required in the AMI"; exit 1; }
      - command -v gh >/dev/null 2>&1 || { echo "gh is required in the AMI"; exit 1; }

  pre_build:
    commands:
      - echo "Unity build starting"
      - git lfs pull
      - test -n "$GITHUB_REPO"
      - test -n "$UNITY_PATH"
      - test -x "$UNITY_PATH"
      - test -n "$witToken"
      - test -n "$witServerToken"
      - if [ -z "${photonAppId:-}" ]; then echo "photonAppId is empty. Photon injection is skipped."; fi
      - |
        if [ -n "${CODEBUILD_WEBHOOK_HEAD_REF:-}" ]; then
          RELEASE_TAG="${CODEBUILD_WEBHOOK_HEAD_REF#refs/tags/}"
        elif [ -n "${RELEASE_TAG:-}" ]; then
          RELEASE_TAG="${RELEASE_TAG}"
        else
          echo "RELEASE_TAG is required for manual builds."
          exit 1
        fi
        case "$RELEASE_TAG" in
          v[0-9]*.[0-9]*.[0-9]*) ;;
          *)
            echo "Invalid RELEASE_TAG: $RELEASE_TAG"
            exit 1
            ;;
        esac
        export RELEASE_TAG
        export OUTPUT_APK_PATH="Builds/${OUTPUT_APK_BASENAME}-${RELEASE_TAG}.apk"
        echo "Resolved RELEASE_TAG=$RELEASE_TAG"
      - echo "Using cache namespace: ${CACHE_NAMESPACE:-default}"

  build:
    commands:
      - mkdir -p "$(dirname \"$OUTPUT_APK_PATH\")"
      - |
        if [ -n "${photonAppId:-}" ]; then
          "$UNITY_PATH" \
            -batchmode \
            -nographics \
            -quit \
            -projectPath "$CODEBUILD_SRC_DIR" \
            -buildTarget Android \
            -executeMethod "$UNITY_BUILD_METHOD" \
            -witToken "$witToken" \
            -witServerToken "$witServerToken" \
            -photonAppId "$photonAppId" \
            -logFile "$CODEBUILD_SRC_DIR/unity-build.log"
        else
          "$UNITY_PATH" \
            -batchmode \
            -nographics \
            -quit \
            -projectPath "$CODEBUILD_SRC_DIR" \
            -buildTarget Android \
            -executeMethod "$UNITY_BUILD_METHOD" \
            -witToken "$witToken" \
            -witServerToken "$witServerToken" \
            -logFile "$CODEBUILD_SRC_DIR/unity-build.log"
        fi
      - |
        if [ -f "$CODEBUILD_SRC_DIR/$OUTPUT_APK_PATH" ]; then
          echo "APK exists at requested path: $OUTPUT_APK_PATH"
        elif [ -f "$CODEBUILD_SRC_DIR/$SOURCE_APK_PATH" ]; then
          mv "$CODEBUILD_SRC_DIR/$SOURCE_APK_PATH" "$CODEBUILD_SRC_DIR/$OUTPUT_APK_PATH"
          echo "Renamed APK from $SOURCE_APK_PATH to $OUTPUT_APK_PATH"
        else
          echo "APK not found at either $OUTPUT_APK_PATH or $SOURCE_APK_PATH"
          exit 1
        fi

  post_build:
    commands:
      - cat "$CODEBUILD_SRC_DIR/unity-build.log" || true
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
          echo "$GITHUB_TOKEN" | gh auth login --with-token
          gh release view "$RELEASE_TAG" --repo "$GITHUB_REPO" >/dev/null 2>&1 || \
            gh release create "$RELEASE_TAG" --repo "$GITHUB_REPO" --title "$RELEASE_TAG" --notes "Automated Unity Android build"
          gh release upload "$RELEASE_TAG" "$CODEBUILD_SRC_DIR/$OUTPUT_APK_PATH" --repo "$GITHUB_REPO" --clobber
        fi

artifacts:
  files:
    - Builds/*.apk
  discard-paths: no

cache:
  paths:
    - "Library/**/*"
    - "/home/ubuntu/.cache/unity3d/**/*"
    - "/home/ubuntu/.gradle/caches/**/*"
